config/routes.rb
Paporeto::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
    resources :categories
    resources :articles, path: 'artigos', path_names: {new: 'novo', edit: 'editar'}
  end

  root 'admin/articles#index'

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :category, presence: true

  uploads_one :picture, thumb: [100, 100], regular: [600, 300]

  belongs_to :category

  paginates_per 5

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.page(params[:page]).per(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.attach_picture(params[:picture_id])

    respond_to do |format|
      if @article.save
        format.html { redirect_to [:admin, @article], notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article.attach_picture(params[:picture_id])

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to [:admin, @article], notice: 'Artigo atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :summary, :body, :category_id)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.page(params[:page]).per(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.attach_picture(params[:picture_id])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article.attach_picture(params[:picture_id])

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Artigo atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :summary, :body, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.slim
= simple_form_for([:admin, @article]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.uploader :picture, preview: :regular
    = f.association :category, prompt: "Escolha uma categoria"
    = f.input :summary
    = f.input :body, input_html: {class: 'input-xxlarge', rows: 10}

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Cancelar', admin_articles_path, class: 'btn'

app/views/admin/articles/edit.html.slim
h1 Editar Artigo

== render 'form'

app/views/admin/articles/index.html.slim
h1 Artigos

table.table
  tr
    th Título
    th Resumo
    td Categoria
    th

  - @articles.each do |article|
    tr
      td = article.title
      td = article.summary
      td = article.category.name
      td
        .btn-group
          = link_to 'Ver', [:admin, article], class: 'btn'
          = link_to 'Editar', edit_admin_article_path(article), class: 'btn'
          = link_to 'Excluir', [:admin, article], :confirm => 'tem certeza?', :method => :delete, class: 'btn'

= paginate @articles, theme: 'twitter-bootstrap'

br

= link_to 'Novo Artigo', new_admin_article_path, class: 'btn btn-primary'

app/views/admin/articles/new.html.slim
h1 Novo Artigo

== render 'form'

app/views/admin/articles/show.html.slim
h1 = @article.title
p = @article.summary
p
  strong = @article.category.try :name

= img @article.picture.regular if @article.picture?

hr
p = simple_format @article.body

= link_to 'Voltar', admin_articles_path, class: 'btn'