config/routes.rb
Paporeto::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
    resources :categories
    resources :articles, path: 'artigos', path_names: {new: 'novo', edit: 'editar'}
  end

  root 'admin/articles#index'

  mount Uploadbox::Engine => '/uploadbox', as: :uploadbox

end

app/views/layouts/application.slim
doctype html
html
  head
    title Paporeto
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .navbar.navbar-inverse.navbar-static-top
      .navbar-inner
        = link_to 'Paporeto', root_path, class: 'brand'

        -if current_user
          ul.nav
            li class="#{'active' if params[:controller] =~ /articles/}"
              = link_to 'Artigos', admin_articles_path
            li class="#{'active' if params[:controller] =~ /categories/}"
              = link_to 'Categorias', admin_categories_path
            li class="#{'active' if params[:controller] =~ /users/}"
              = link_to 'Usuários', admin_users_path

          ul.nav.pull-right
            li
              = link_to current_user.email, '#'
            li
              =link_to 'Sair', destroy_user_session_path, method: :delete

    .container

      - if notice
       .alert
         button type="button" class="close" data-dismiss="alert" &times;
         = notice

      - if alert
          .alert.alert-error
            button type="button" class="close" data-dismiss="alert" &times;
            = alert

      = yield